# AppSpec 파일의 버전을 지정
version: 0.0

# 배포할 인스턴스의 운영 체제 값을 지정
os: linux

# 배포의 설치 이벤트 중 인스턴스에 복사해야 하는 파일의 이름을 지정
files:
  # 인스턴스에 복사할 수정의 파일 또는 디렉터리를 식별
  # "/" 수정 버전의 모든 파일이 인스턴스에 복사
  - source: /
    # 인스턴스에서 파일이 복사되어야 하는 위치를 식별
    destination: /home/ubuntu/next

# CodeDeploy가 배포 대상 위치에 이미 존재하지만 이전에 성공한 배포의 일부가 아닌 파일을 처리하는 방식을 지정
# 현재 배포 중인 애플리케이션 수정 버전의 파일 버전이 인스턴스에 이미 있는 버전을 대체
file_exists_behavior: OVERWRITE

# 'files' 섹션의 파일 및 디렉터리/폴더가 인스턴스에 복사된 후 이러한 파일 및 디렉터리/폴더에 특수 권한(있는 경우)이 어떻게 적용되어야 하는지를 지정
permissions:
  # 파일 시스템 객체가 인스턴스로 복사된 후 지정한 권한이 적용되는 파일 시스템 객체 세트(파일 또는 디렉터리/폴더)
  - object: /home/ubuntu/next
    # object의 소유자 이름
    owner: ubuntu
    # object의 그룹 이름
    group: ubuntu
    # object에 적용할 권한을 지정하는 숫자 값
    mode: 755
hooks:
  # 배포 수명 주기 이벤트의 이름
  # 애플리케이션 구성 또는 파일 권한 변경과 같은 작업에 이 배포 수명 주기 이벤트를 사용할 수 있습니다.
  # 애플리케이션의 새 버전이 설치된 후에 실행할 작업을 정의
  AfterInstall:
    # 수정의 스크립트 파일 번들 위치
    - location: deploy.sh
      # 스크립트가 실패로 간주되기 전에 실행할 수 있는 기간(초)
      timeout: 60
      # 스크립트 실행 시 가장하는 사용자. 기본적으로 인스턴스에서 실행 중인 CodeDeploy 에이전트
      runas: ubuntu
